### ISSUE TITLE
Request Collaborator Access

### ISSUE THREAD

**Issue by ids1024** [ids1024/archcommunitytags#1]
Post here to request that you are added to the repository as a collaborator.  At the moment, anyone who asks here will be given access.  This will change if a better way to submit tags is created or if this becomes a problem.

**Comment by thiagowfx** [comment]
_requesting collaborator access_

**Comment by ids1024** [comment]
@thiagowfx Done.

**Comment by thiagowfx** [comment]
Thanks. I'll push eventual commits to the 'thiagowfx' branch, so you might review them before merging to master.

**Comment by ids1024** [comment]
You can push straight to master if you want.  Alternatively, you could push additions of tags to master and things that could be argued about (editing the README, renaming tags, etc.) to your own branch.
