### ISSUE TITLE
Quick and dirty hack for counting the tags

### ISSUE THREAD

**Issue by thiagowfx** [ids1024/archcommunitytags#2]
```
cat $(ls -I README.md) | sed -e '/^$/d' -e '/^#/d' | sort | uniq -c | sort
```

It can be used for finding typos too...for example, I found a 'filemnger' typo (or something like that).

**Comment by ids1024** [comment]
Didn't you see the --tags command I added to communitytags?

Edit: You may also want to look at the scripts in the extra directory of archcommunitytags-tools.

**Comment by ids1024** [comment]
Do you think it would be a good idea to move tags to a `tags` sub-directory?  That way the README.md, .pacnet etc. do not have to be explicitly excluded from things like this.

**Comment by thiagowfx** [comment]
About your second comment: it would be a good idea indeed, to avoid thinks such as 

```
if i.startswith('.') or i == 'README.md':
    continue
```

Forget my hack -- I just saw your comment on the forums about the `--tags` now. Closing this.
