### ISSUE TITLE
About package renames

### ISSUE THREAD

**Issue by thiagowfx** [ids1024/archcommunitytags#3]
Hi Ian,

I was thinking: what should be done whenever a package in the official repos gets renamed?

For example, I saw you added `kdegraphics-okular` -- I myself thought of it in the PDF category. However, I didn't add it because I know it would be soon renamed to simply `okular`, due to the transition from KDE4 to KDE5 frameworks.
1. This creates my question. Maybe there should be a way to detect which packages are not present in any user repos (defined in `/etc/pacman.conf`)?
2. Or, maybe there should be a concept of package aliases. Even that `kdegraphics-okular` ceases to exist soon, its name is unlikely to be taken again. So, instead of renaming the file in archcommunitytags to `okular`, we could somehow create an alias for it. Maybe a simply symlink.

What do you think?

**Comment by ids1024** [comment]
1. The tagsnopkg script in the extra directory of archcommunitytags-tools does this.  It is also good for spotting  typos.
2. I think renaming would be easier. It is simple enough to rename a single file.  I think this would just add unnecessary complexity.

**Comment by ids1024** [comment]
Actually, a script could automate renaming by looking for a package that replaces it.  For example, `communitytags replace=enlightenment17` shows that `enlightenment` replaces the `enlightenment17` package.

**Comment by ids1024** [comment]
I have adapted the script so that it automatically handles renamed packages when the new packages defines `replaces`.  If you rename `enlightenment` to `enlightenment17` in the tags directory, communitytags will list `enlightenment` (the new package) under `communitytags tag=wm`.

**Comment by thiagowfx** [comment]
Nice! I think `replaces` handles the situation very well indeed. Closing.

**Comment by ids1024** [comment]
It is probably good to also rename the file, but this makes it so it is not urgent (and a way to figure out what to rename it to).
